#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Medyx_sanKT")]
public partial class BenhAnDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertLinQ_BenhNhan_TienSu_San_C(LinQ_BenhNhan_TienSu_San_C instance);
  partial void UpdateLinQ_BenhNhan_TienSu_San_C(LinQ_BenhNhan_TienSu_San_C instance);
  partial void DeleteLinQ_BenhNhan_TienSu_San_C(LinQ_BenhNhan_TienSu_San_C instance);
  #endregion
	
	public BenhAnDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Medyx_YHCTTWConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public BenhAnDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BenhAnDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BenhAnDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BenhAnDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<LinQ_BenhNhan_TienSu_San_C> LinQ_BenhNhan_TienSu_San_Cs
	{
		get
		{
			return this.GetTable<LinQ_BenhNhan_TienSu_San_C>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BenhNhan_TienSu_San_C")]
public partial class LinQ_BenhNhan_TienSu_San_C : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _MaBN;
	
	private int _STT;
	
	private string _ThoigianThainghen;
	
	private string _Tuoithai;
	
	private string _DienbienThai;
	
	private string _Cachde;
	
	private string _Tresosinh;
	
	private string _HauSan;
	
	private string _Khac;
	
	private string _MaMay;
	
	private System.Nullable<bool> _Huy;
	
	private System.Nullable<System.DateTime> _NgaySD;
	
	private string _NguoiSD;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBNChanging(string value);
    partial void OnMaBNChanged();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnThoigianThainghenChanging(string value);
    partial void OnThoigianThainghenChanged();
    partial void OnTuoithaiChanging(string value);
    partial void OnTuoithaiChanged();
    partial void OnDienbienThaiChanging(string value);
    partial void OnDienbienThaiChanged();
    partial void OnCachdeChanging(string value);
    partial void OnCachdeChanged();
    partial void OnTresosinhChanging(string value);
    partial void OnTresosinhChanged();
    partial void OnHauSanChanging(string value);
    partial void OnHauSanChanged();
    partial void OnKhacChanging(string value);
    partial void OnKhacChanged();
    partial void OnMaMayChanging(string value);
    partial void OnMaMayChanged();
    partial void OnHuyChanging(System.Nullable<bool> value);
    partial void OnHuyChanged();
    partial void OnNgaySDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySDChanged();
    partial void OnNguoiSDChanging(string value);
    partial void OnNguoiSDChanged();
    #endregion
	
	public LinQ_BenhNhan_TienSu_San_C()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBN", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string MaBN
	{
		get
		{
			return this._MaBN;
		}
		set
		{
			if ((this._MaBN != value))
			{
				this.OnMaBNChanging(value);
				this.SendPropertyChanging();
				this._MaBN = value;
				this.SendPropertyChanged("MaBN");
				this.OnMaBNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int STT
	{
		get
		{
			return this._STT;
		}
		set
		{
			if ((this._STT != value))
			{
				this.OnSTTChanging(value);
				this.SendPropertyChanging();
				this._STT = value;
				this.SendPropertyChanged("STT");
				this.OnSTTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoigianThainghen", DbType="NVarChar(150)")]
	public string ThoigianThainghen
	{
		get
		{
			return this._ThoigianThainghen;
		}
		set
		{
			if ((this._ThoigianThainghen != value))
			{
				this.OnThoigianThainghenChanging(value);
				this.SendPropertyChanging();
				this._ThoigianThainghen = value;
				this.SendPropertyChanged("ThoigianThainghen");
				this.OnThoigianThainghenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuoithai", DbType="NVarChar(50)")]
	public string Tuoithai
	{
		get
		{
			return this._Tuoithai;
		}
		set
		{
			if ((this._Tuoithai != value))
			{
				this.OnTuoithaiChanging(value);
				this.SendPropertyChanging();
				this._Tuoithai = value;
				this.SendPropertyChanged("Tuoithai");
				this.OnTuoithaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienbienThai", DbType="NVarChar(50)")]
	public string DienbienThai
	{
		get
		{
			return this._DienbienThai;
		}
		set
		{
			if ((this._DienbienThai != value))
			{
				this.OnDienbienThaiChanging(value);
				this.SendPropertyChanging();
				this._DienbienThai = value;
				this.SendPropertyChanged("DienbienThai");
				this.OnDienbienThaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cachde", DbType="NVarChar(50)")]
	public string Cachde
	{
		get
		{
			return this._Cachde;
		}
		set
		{
			if ((this._Cachde != value))
			{
				this.OnCachdeChanging(value);
				this.SendPropertyChanging();
				this._Cachde = value;
				this.SendPropertyChanged("Cachde");
				this.OnCachdeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tresosinh", DbType="NVarChar(50)")]
	public string Tresosinh
	{
		get
		{
			return this._Tresosinh;
		}
		set
		{
			if ((this._Tresosinh != value))
			{
				this.OnTresosinhChanging(value);
				this.SendPropertyChanging();
				this._Tresosinh = value;
				this.SendPropertyChanged("Tresosinh");
				this.OnTresosinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HauSan", DbType="NVarChar(50)")]
	public string HauSan
	{
		get
		{
			return this._HauSan;
		}
		set
		{
			if ((this._HauSan != value))
			{
				this.OnHauSanChanging(value);
				this.SendPropertyChanging();
				this._HauSan = value;
				this.SendPropertyChanged("HauSan");
				this.OnHauSanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khac", DbType="NVarChar(50)")]
	public string Khac
	{
		get
		{
			return this._Khac;
		}
		set
		{
			if ((this._Khac != value))
			{
				this.OnKhacChanging(value);
				this.SendPropertyChanging();
				this._Khac = value;
				this.SendPropertyChanged("Khac");
				this.OnKhacChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMay", DbType="NVarChar(20)")]
	public string MaMay
	{
		get
		{
			return this._MaMay;
		}
		set
		{
			if ((this._MaMay != value))
			{
				this.OnMaMayChanging(value);
				this.SendPropertyChanging();
				this._MaMay = value;
				this.SendPropertyChanged("MaMay");
				this.OnMaMayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Huy", DbType="Bit")]
	public System.Nullable<bool> Huy
	{
		get
		{
			return this._Huy;
		}
		set
		{
			if ((this._Huy != value))
			{
				this.OnHuyChanging(value);
				this.SendPropertyChanging();
				this._Huy = value;
				this.SendPropertyChanged("Huy");
				this.OnHuyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySD", DbType="DateTime")]
	public System.Nullable<System.DateTime> NgaySD
	{
		get
		{
			return this._NgaySD;
		}
		set
		{
			if ((this._NgaySD != value))
			{
				this.OnNgaySDChanging(value);
				this.SendPropertyChanging();
				this._NgaySD = value;
				this.SendPropertyChanged("NgaySD");
				this.OnNgaySDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiSD", DbType="NVarChar(6)")]
	public string NguoiSD
	{
		get
		{
			return this._NguoiSD;
		}
		set
		{
			if ((this._NguoiSD != value))
			{
				this.OnNguoiSDChanging(value);
				this.SendPropertyChanging();
				this._NguoiSD = value;
				this.SendPropertyChanged("NguoiSD");
				this.OnNguoiSDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
