#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MedYX_Hue")]
public partial class HL7CoreDataDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public HL7CoreDataDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Medyx_YHCTTWConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public HL7CoreDataDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HL7CoreDataDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HL7CoreDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HL7CoreDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DanhSachHsba")]
	public ISingleResult<sp_DanhSachHsbaResult> sp_DanhSachHsba([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(12)")] string maba)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maba);
		return ((ISingleResult<sp_DanhSachHsbaResult>)(result.ReturnValue));
	}
    [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.spACCOUNT_Get")]
    public ISingleResult<spACCOUNT_Get> spACCOUNT_Get([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "NVarChar(100)")] string ACCOUNT)
    {
        IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ACCOUNT);
        return ((ISingleResult<spACCOUNT_Get>)(result.ReturnValue));
    }
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_TestMenu")]
	public ISingleResult<sp_TestMenuResult> sp_TestMenu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccountName", DbType="NVarChar(50)")] string accountName)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), accountName);
		return ((ISingleResult<sp_TestMenuResult>)(result.ReturnValue));
	}
}

public partial class sp_DanhSachHsbaResult
{
	
	private string _Column1;
	
	public sp_DanhSachHsbaResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="NVarChar(20)")]
	public string Column1
	{
		get
		{
			return this._Column1;
		}
		set
		{
			if ((this._Column1 != value))
			{
				this._Column1 = value;
			}
		}
	}
}
public partial class spACCOUNT_Get
{
    public Int32 Ordernumber { get; set; }
    public String GhiChu { get; set; }
    public String MaNV { get; set; }
    public String Account { get; set; }
    public String Password { get; set; }
    public String MaKhoaLS { get; set; }
    public String MaKhoaCLS { get; set; }
    public String MaKho { get; set; }
    public Boolean AllMaKho { get; set; }
    public Boolean AllMaKhoaCLS { get; set; }
    public Boolean AllMaKhoaLS { get; set; }
    public String QuyenDTuong { get; set; }
    public Boolean AllQuyenDTuong { get; set; }
    public String MaMay { get; set; }
    public Boolean Huy { get; set; }
    public DateTime NgaySD { get; set; }
    public String NguoiSD { get; set; }
    public Boolean Qadmin { get; set; }
    public Boolean Qsgia { get; set; }
    public String HoTen { get; set; }
    public String tennguoisd { get; set; }

    public spACCOUNT_Get()
    {
        GhiChu = "";
        MaNV = "";
        Account = "";
        Password = "";
        MaKhoaLS = "";
        MaKhoaCLS = "";
        MaKho = "";
        AllMaKho = false;
        AllMaKhoaCLS = false;
        AllMaKhoaLS = false;
        QuyenDTuong = "";
        AllQuyenDTuong = false;
        MaMay = "";
        Huy = false;
        NgaySD = new DateTime();
        NguoiSD = "";
        Qadmin = false;
        Qsgia = false;
        HoTen = "";
        tennguoisd = "";
        Ordernumber = 0;
    }
}
public partial class sp_TestMenuResult
{
	
	private string _MaMN;
	
	private string _TenMN;
	
	private byte _Cap;
	
	private string _TenCNang;
	
	private string _ClassName;
	
	private string _ShortcutKeyIndex;
	
	private string _Separator;
	
	private string _ShortCutKey;
	
	private string _MenuIcon;
	
	private string _ToolBarIndex;
	
	private string _ToolTip;
	
	private string _HelpString;
	
	private string _Path;
	
	private byte _QUYENMN;
	
	private string _MaRole;
	
	public sp_TestMenuResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMN", DbType="NVarChar(9) NOT NULL", CanBeNull=false)]
	public string MaMN
	{
		get
		{
			return this._MaMN;
		}
		set
		{
			if ((this._MaMN != value))
			{
				this._MaMN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMN", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string TenMN
	{
		get
		{
			return this._TenMN;
		}
		set
		{
			if ((this._TenMN != value))
			{
				this._TenMN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cap", DbType="TinyInt NOT NULL")]
	public byte Cap
	{
		get
		{
			return this._Cap;
		}
		set
		{
			if ((this._Cap != value))
			{
				this._Cap = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCNang", DbType="NVarChar(20)")]
	public string TenCNang
	{
		get
		{
			return this._TenCNang;
		}
		set
		{
			if ((this._TenCNang != value))
			{
				this._TenCNang = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string ClassName
	{
		get
		{
			return this._ClassName;
		}
		set
		{
			if ((this._ClassName != value))
			{
				this._ClassName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortcutKeyIndex", DbType="NVarChar(100)")]
	public string ShortcutKeyIndex
	{
		get
		{
			return this._ShortcutKeyIndex;
		}
		set
		{
			if ((this._ShortcutKeyIndex != value))
			{
				this._ShortcutKeyIndex = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Separator", DbType="NVarChar(100)")]
	public string Separator
	{
		get
		{
			return this._Separator;
		}
		set
		{
			if ((this._Separator != value))
			{
				this._Separator = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortCutKey", DbType="NVarChar(100)")]
	public string ShortCutKey
	{
		get
		{
			return this._ShortCutKey;
		}
		set
		{
			if ((this._ShortCutKey != value))
			{
				this._ShortCutKey = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuIcon", DbType="NVarChar(100)")]
	public string MenuIcon
	{
		get
		{
			return this._MenuIcon;
		}
		set
		{
			if ((this._MenuIcon != value))
			{
				this._MenuIcon = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToolBarIndex", DbType="NVarChar(100)")]
	public string ToolBarIndex
	{
		get
		{
			return this._ToolBarIndex;
		}
		set
		{
			if ((this._ToolBarIndex != value))
			{
				this._ToolBarIndex = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToolTip", DbType="NVarChar(100)")]
	public string ToolTip
	{
		get
		{
			return this._ToolTip;
		}
		set
		{
			if ((this._ToolTip != value))
			{
				this._ToolTip = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HelpString", DbType="NVarChar(100)")]
	public string HelpString
	{
		get
		{
			return this._HelpString;
		}
		set
		{
			if ((this._HelpString != value))
			{
				this._HelpString = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Path", DbType="NVarChar(MAX)")]
	public string Path
	{
		get
		{
			return this._Path;
		}
		set
		{
			if ((this._Path != value))
			{
				this._Path = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUYENMN", DbType="TinyInt NOT NULL")]
	public byte QUYENMN
	{
		get
		{
			return this._QUYENMN;
		}
		set
		{
			if ((this._QUYENMN != value))
			{
				this._QUYENMN = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaRole", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
	public string MaRole
	{
		get
		{
			return this._MaRole;
		}
		set
		{
			if ((this._MaRole != value))
			{
				this._MaRole = value;
			}
		}
	}
}
#pragma warning restore 1591
